site_name: NGS analysis tutorials
pages:
- [index.md, Home]
- [gvlsetup.md, Initial setup]
- [fastqc.md, FastQC]
- [demuxing.md, Custom demultiplexing]
- [assembly.md, Genome assembly with SPAdes]
- [annotate.md, Genome annotation with Prokka]
- [mauve.md, Comparing genomes with Mauve]
- [nectar_cloud.md, Using the NeCTAR cloud]
- [instance_startup.md, Starting a NeCTAR instance]
- [filezilla.md, FileZilla secure FTP]
- [marker_phylogeny.md, Marker gene phylogeny]
- [uts_networking.md, UTS network settings]
- [alignment.md, Dynamic programming alignment]
theme: readthedocs
